spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/securityDemo?useSSL=false
  session:
    store-type: none
  output:
    ansi:
      enabled: always
  security:
    user:
      name: zsz
      password: 123456
server:
  port: 8060



