spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/securitydemo?useSSL=false
    username: root
  session:
    store-type: none
  output:
    ansi:
      enabled: always
server:
  port: 8060

bsb:
  security:
    browser:
      loginPage: /signIn.html
#      loginType: REDIRECT
    code:
      imageCodeProperties:
        length: 4
        width: 50
        url: /user/*