spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/securityDemo?useSSL=false
  session:
    store-type: none
server:
  port: 8060
  servlet:
    context-path: /security



